site_name: Manual de Códigos Modulo Rriet
site_url: https://github.com/SilverPsychoo/Modulo-Rriet
site_description: "Manual de códigos de Arduino del módulo Rriet, con ejemplos listos para copiar y pegar."
site_author: "Robotec"

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'img/Robotec.PNG'
  favicon: 'img/Robotec.ico'
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
  copyright: "© 2025 Robotec. Todos los derechos reservados."

nav:
  - Inicio: index.md
  - Sensores:
      - Sensor Ultrasonico HC-SR04: Sensores/ultrasonico.md
      - Sensor IR: Sensores/infrarrojo.md
      - Sensor de Temperatura (DHT11): Sensores/temperatura.md
      - Sensor de Humedad en la Tierra: Sensores/humedadtierra.md
      - Sensor de Humedad: Sensores/humedad.md
      - Sensor de Movimiento PIR: Sensores/movimiento.md
      - Sensor de Flama: Sensores/flama.md
      - Sensor de Gas: Sensores/gas.md
  - Actuadores:
      - Servo Motor: Actuadores/servo.md
      - Motor a pasos: Actuadores/motorpasos.md
      - LED RGB: Actuadores/rgb.md
      - Relevador (Relay): Actuadores/rele.md
      - Laser (HW-493): Actuadores/laser.md
      - Buzzer: Actuadores/buzzer.md
  - Displays:
      - LCD: Pantalla/lcd.md
      - Matriz LED: Pantalla/matriz.md
      - Display 7 segmentos (74HC595): Pantalla/segmentos.md
  - Otros módulos:
      - Módulo Bluetooth HC-05: Otros/bluetooth.md
      - Potenciometro: Otros/pote.md
      - Joystick Analógico: Otros/joystick.md

plugins:
  - search
